AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Payment processing with Lambda Durable Functions

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  RiskScoreThreshold:
    Type: String
    Default: "0.7"
  ApprovalTimeoutHours:
    Type: Number
    Default: 24

Globals:
  Function:
    Runtime: python3.14
    Architectures:
      - x86_64
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
    Tags:
      Project: payment-processor
      Environment: !Ref Environment

Resources:
  # DynamoDB Table for Payments
  PaymentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'payments-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: payment_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: payment_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # Payment Processor Function
  PaymentProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'payment-processor-${Environment}'
      Handler: app.lambda_handler
      CodeUri: src/
      MemorySize: 256
      Timeout: 60
      AutoPublishAlias: live
      DurableConfig:
        ExecutionTimeout: 3600
        RetentionPeriodInDays: 7
      Environment:
        Variables:
          RISK_SCORE_THRESHOLD: !Ref RiskScoreThreshold
          APPROVAL_TIMEOUT_HOURS: !Ref ApprovalTimeoutHours
          ENVIRONMENT: !Ref Environment
          PAYMENTS_TABLE: !Ref PaymentsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PaymentsTable
        - Statement:
          - Effect: Allow
            Action:
              - lambda:CheckpointDurableExecutions
              - lambda:GetDurableExecutionState
            Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:payment-processor-${Environment}:*'

  # Admin API Function
  AdminApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'payment-admin-api-${Environment}'
      Handler: admin_api.lambda_handler
      CodeUri: src/
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          PAYMENTS_TABLE: !Ref PaymentsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PaymentsTable
        - Statement:
          - Effect: Allow
            Action:
              - lambda:SendDurableExecutionCallbackSuccess
              - lambda:SendDurableExecutionCallbackFailure
            Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:payment-processor-${Environment}:*'
      Events:
        GetPending:
          Type: Api
          Properties:
            Path: /pending
            Method: GET
            RestApiId: !Ref AdminApi
        GetPayments:
          Type: Api
          Properties:
            Path: /payments
            Method: GET
            RestApiId: !Ref AdminApi
        Approve:
          Type: Api
          Properties:
            Path: /approve
            Method: POST
            RestApiId: !Ref AdminApi
        Reject:
          Type: Api
          Properties:
            Path: /reject
            Method: POST
            RestApiId: !Ref AdminApi
        Clear:
          Type: Api
          Properties:
            Path: /clear
            Method: POST
            RestApiId: !Ref AdminApi
        Options:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: OPTIONS
            RestApiId: !Ref AdminApi

  AdminApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"

  # CloudWatch Alarm
  PaymentProcessorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'payment-processor-${Environment}-errors'
      AlarmDescription: Alarm when payment processor has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref PaymentProcessorFunction

Outputs:
  FunctionArn:
    Description: Payment Processor Function ARN
    Value: !GetAtt PaymentProcessorFunction.Arn
  FunctionAlias:
    Description: Live alias for invocation
    Value: !Sub '${PaymentProcessorFunction.Arn}:live'
  AdminApiUrl:
    Description: Admin API URL
    Value: !Sub 'https://${AdminApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
  PaymentsTable:
    Description: DynamoDB Payments Table
    Value: !Ref PaymentsTable
  AlarmArn:
    Description: CloudWatch Alarm ARN
    Value: !GetAtt PaymentProcessorAlarm.Arn
